spring:
  application:
    name: pul-api
  cache:
    type: redis
    redis:
      time-to-live: "P1D"
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: 'jdbc:postgresql://127.0.0.1:5432/pul'
    username: 'pul'
    password: 'L0ngL1vE@CPC'
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      enabled: true
  redis:
    host: localhost
    port: 6379
    database: 1

server:
  port: 8181

rserver:
  host: '127.0.0.1'
  port: 6311

predict:
  docker-image: 'pul-predict:1.0.0'
  docker-cpu: 1
  docker-api-version: '1.39'
  docker-memory: 100000000
  max-retry-times: 3
  reserve-result-days: 7
  reference-path: "/Volumes/portable/me/pul/predict"
  input-path: "/Volumes/portable/me/pul/predict/test_input"
  output-path: "/Volumes/portable/me/pul/predict/test_output"
