spring:
  application:
    name: pul-api
  cache:
    type: redis
    redis:
      time-to-live: "P5D"
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: 'jdbc:postgresql://${POSTGRE_HOST}:${POSTGRE_PORT}/${POSTGRE_DB}'
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASS}
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      enabled: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: ${REDIS_DB}

server:
  port: ${PORT}

rserver:
  host: ${RSERVER_HOST}
  port: ${RSERVER_PORT}

predict:
  docker-image: ${PREDICT_IMAGE}
  docker-cpu: ${PREDICT_DOCKER_CPU}
  docker-memory: ${PREDICT_DOCKER_MEM}
  max-retry-times: ${PREDICT_RETRY_TIMES}
  reserve-result-days: ${PREDICT_RESERVE_DAYS}
  reference-path: ${PREDICT_REFERENCE_PATH}
  input-path: ${PREDICT_INPUT_PATH}
  output-path: ${PREDICT_OUTPUT_PATH}
