spring:
  application:
    name: pul-api
  cache:
    type: redis
    redis:
      time-to-live: "P30D"
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: 'jdbc:postgresql://127.0.0.1:5432/pul'
    username: 'pul'
    password: 'L0ngL1vE@CPC'
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      enabled: true
  redis:
    host: localhost
    port: 6379
    database: 1

server:
  port: 8081

rserver:
  host: '127.0.0.1'
  port: 6311