version: '3'

services:
  db:
    image: postgres:13.3-parquet-fdw
    restart: always
    expose:
      - "5432:5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pul
      POSTGRES_PASSWORD: "L0ngL1vE@CPC"
      POSTGRES_DB: pul
    volumes:
      - "./db:/var/lib/postgresql/data"
      - "./external:/mnt/data"
