version: '3'

services:
  db:
    image: postgres:13.3-parquet-fdw
    restart: always
    expose:
      - "5432:5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pul
      POSTGRES_PASSWORD: "L0ngL1vE@CPC"
      POSTGRES_DB: pul
    volumes:
      - "./db:/var/lib/postgresql/data"
      - "./external:/mnt/data"
  rserver:
    image: rserver:4.1.0
    restart: always
    expose:
      - "6311:6311"
    ports:
      - "6311:6311"
  redis:
    image: redis:4.0.13
    expose:
      - "6379:6379"
    ports:
      - "6379:6379"

  sql-migration:
    image: pul-sql-migration:2.0.0
    entrypoint:
      - flyway
      - migrate
      - -X
    environment:
      FLYWAY_USER: 'pul'
      FLYWAY_URL: 'jdbc:postgresql://db:5432/pul'
      FLYWAY_PASSWORD: 'L0ngL1vE@CPC'
      FLYWAY_SCHEMAS: 'public'
    depends_on:
      - db
  pul-api:
    image: pul-api:2.0.0
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      PORT: '8080'
      POSTGRE_HOST: 'db'
      POSTGRE_PORT: '5432'
      POSTGRE_DB: 'pul'
      POSTGRE_USER: 'pul'
      POSTGRE_PASS: 'L0ngL1vE@CPC'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      REDIS_DB: '1'
      RSERVER_HOST: 'rserver'
      RSERVER_PORT: 6311
    depends_on:
      - db
      - rserver
      - redis
    links:
      - db
      - rserver
      - redis
  pul:
    image: pul:2.0.0
    expose:
      - "81:80"
    ports:
      - "81:80"
    depends_on:
      - pul-api
    volumes:
      - "./static:/data/static"
    links:
      - pul-api

